image: debian/bullseye
packages:
  - mercurial
  - python3-pip
  - postgresql
  - emacs-nox
sources:
  - hg+https://hg.sr.ht/~pythonian/tshistory_supervision
  - hg+https://hg.sr.ht/~pythonian/tshistory_formula
  - hg+https://hg.sr.ht/~pythonian/tshistory_xl
  - hg+https://hg.sr.ht/~pythonian/rework
  - hg+https://hg.sr.ht/~pythonian/tshistory_refinery
tasks:
  - install: |
      export PATH=$PATH:~/.local/bin:/usr/lib/postgresql/13/bin
      pip3 install pandas==1.4.4
      pip3 install numpy==1.23.4
      pip3 install tox wheel setuptools webtest pytest_sa_pg pystuck --quiet
      pip3 install -e tshistory --prefer-binary
      pip3 install -e tshistory_supervision --prefer-binary
      pip3 install -e tshistory_formula --prefer-binary
      pip3 install -e tshistory_xl --prefer-binary
      pip3 install -e rework --prefer-binary
      pip3 install -e tshistory_refinery --prefer-binary
  - run-tests: |
      export PATH=$PATH:~/.local/bin:/usr/lib/postgresql/13/bin
      pip3 install pytest pytest_sa_pg responses
      cd tshistory
      pytest
      cd ../tshistory_supervision
      pytest
      cd ../tshistory_formula
      pytest
      cd ../tshistory_xl
      pytest
      cd ../rework
      pytest
      cd ../tshistory_refinery
      pytest
