image: debian/bullseye
packages:
  - mercurial
  - python3-pip
  - postgresql
  - emacs-nox
sources:
  - hg+https://hg.sr.ht/~pythonian/tshistory
secrets:
  -  2697538f-6b29-4af7-9fb2-e17694886c3f
tasks:
  - run-tests: |
      export PATH=$PATH:~/.local/bin:/usr/lib/postgresql/13/bin
      pip3 install pip --upgrade
      pip install tox
      cd tshistory
      tox
