[tox]
envlist = root

[testenv]
deps =
    pytest
    responses
    webtest
    ruff
commands =
         tsh --help
         ruff check .
         pytest
install_command = pip install {opts} {packages}
